wailist and internship categories documented and edited
Zummit-Africa-Inc/Web-Page-BE pull request #8
Opened 2022-04-06 11:32 UTC by SunmadeBabafemi

1. waitlist and internship category entities extended to shared entity
2. new migrations generated and ran for both entities
3. Api tags added to both controllers for the swagger UI

2022-04-06 11:32 UTC, SunmadeBabafemi commented
@Chimexx and @andyjrII Kindly review for merging

2022-04-06 11:38 UTC, Chimexx commented on src/intershipCategories/internshipCategories.controllers.ts
>      return ZuAppResponse.Ok(newCategory, "List Of all in internship categories", "201");
Get should be a 200 code not 201

2022-04-06 12:25 UTC, Chimexx requested changes
Look into the stuff I pointed out

2022-04-06 12:25 UTC, Chimexx commented on src/waitlist/dto/waitlist.dto.ts
>    id?: string;
Is there need for id?

2022-04-06 12:55 UTC, SunmadeBabafemi commented on src/waitlist/dto/waitlist.dto.ts
>    id?: string;
i think that can be removed.. thanks

2022-04-06 13:14 UTC, Chimexx approved these changes

2022-04-06 13:14 UTC, Chimexx commented on src/waitlist/dto/waitlist.dto.ts
> +  // id?: string;
I dont't think it's a good idea to leave commented code that won't be used it the future.

2022-04-07 11:38 UTC, PhilemonBrain approved these changes
Nice work

2022-04-07 11:38 UTC, merged